---
# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

name: Snyk Scan Node

on:
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup
        run: |
          echo "Node version is: $(node --version)"
          echo "Yarn version is: $(yarn --version)"
          echo "Running top level install..."

      - name: Install Dependencies
        run: |
          yarn install

      - name: Install Snyk
        run: yarn global add snyk

      - name: Set Results Variable
        id: vars
        run: echo ::set-output name=snyk_results::$(snyk test --org=${{ secrets.SNYK_ORG }} --file=package.json)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Generate Scan Summary
        run: |
          # Send results to the GitHub Action markdown summary page
          cat >> $GITHUB_STEP_SUMMARY <<- EOM
          ### Snyk Snyk Node Audit Report
          Results from the snyk node vulnerabilities report are:
          ```code
          ${{ steps.vars.outputs.snyk_results }}
          ```
          EOM

      - name: Snyk Monitor
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG: ${{ secrets.SNYK_ORG }}
        with:
          command: monitor
          args: --org=${{ secrets.SNYK_ORG }} --file=package.json

      - name: Slack Notification
        uses: ravsamhq/notify-slack-action@v1
        if: always()
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} {workflow} {status_message} for repository <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}> Snyk Results: ${{ steps.vars.outputs.snyk_results }}'
          footer: 'Repository: <{repo_url}|{repo}> | <{workflow_url}|View Workflow>'
          mention_users: 'UH8CHEUQL'
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
